#ifndef _BSP_GPIO_H_
#define _BSP_GPIO_H_

#include <stddef.h>

// Dependencies
#include "platform/gpio/gpio.h"

// Config
#define BSP_GPIO_PIN_PORT_SHIFT 8U
#define BSP_GPIO_PIN_INDEX_MASK 0xFFU
#define BSP_GPIO_PIN(port, pin) ((((size_t)(port)) << BSP_GPIO_PIN_PORT_SHIFT) | ((size_t)(pin) & BSP_GPIO_PIN_INDEX_MASK))

#define BSP_GPIO_PIN_PA0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 0U)
#define BSP_GPIO_PIN_PA1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 1U)
#define BSP_GPIO_PIN_PA2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 2U)
#define BSP_GPIO_PIN_PA3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 3U)
#define BSP_GPIO_PIN_PA4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 4U)
#define BSP_GPIO_PIN_PA5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 5U)
#define BSP_GPIO_PIN_PA6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 6U)
#define BSP_GPIO_PIN_PA7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 7U)
#define BSP_GPIO_PIN_PA8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 8U)
#define BSP_GPIO_PIN_PA9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 9U)
#define BSP_GPIO_PIN_PA10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 10U)
#define BSP_GPIO_PIN_PA11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 11U)
#define BSP_GPIO_PIN_PA12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 12U)
#define BSP_GPIO_PIN_PA13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 13U)
#define BSP_GPIO_PIN_PA14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 14U)
#define BSP_GPIO_PIN_PA15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_A, 15U)

#define BSP_GPIO_PIN_PB0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 0U)
#define BSP_GPIO_PIN_PB1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 1U)
#define BSP_GPIO_PIN_PB2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 2U)
#define BSP_GPIO_PIN_PB3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 3U)
#define BSP_GPIO_PIN_PB4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 4U)
#define BSP_GPIO_PIN_PB5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 5U)
#define BSP_GPIO_PIN_PB6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 6U)
#define BSP_GPIO_PIN_PB7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 7U)
#define BSP_GPIO_PIN_PB8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 8U)
#define BSP_GPIO_PIN_PB9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 9U)
#define BSP_GPIO_PIN_PB10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 10U)
#define BSP_GPIO_PIN_PB11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 11U)
#define BSP_GPIO_PIN_PB12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 12U)
#define BSP_GPIO_PIN_PB13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 13U)
#define BSP_GPIO_PIN_PB14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 14U)
#define BSP_GPIO_PIN_PB15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_B, 15U)

#define BSP_GPIO_PIN_PC0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 0U)
#define BSP_GPIO_PIN_PC1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 1U)
#define BSP_GPIO_PIN_PC2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 2U)
#define BSP_GPIO_PIN_PC3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 3U)
#define BSP_GPIO_PIN_PC4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 4U)
#define BSP_GPIO_PIN_PC5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 5U)
#define BSP_GPIO_PIN_PC6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 6U)
#define BSP_GPIO_PIN_PC7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 7U)
#define BSP_GPIO_PIN_PC8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 8U)
#define BSP_GPIO_PIN_PC9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 9U)
#define BSP_GPIO_PIN_PC10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 10U)
#define BSP_GPIO_PIN_PC11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 11U)
#define BSP_GPIO_PIN_PC12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 12U)
#define BSP_GPIO_PIN_PC13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 13U)
#define BSP_GPIO_PIN_PC14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 14U)
#define BSP_GPIO_PIN_PC15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_C, 15U)

#define BSP_GPIO_PIN_PD0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 0U)
#define BSP_GPIO_PIN_PD1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 1U)
#define BSP_GPIO_PIN_PD2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 2U)
#define BSP_GPIO_PIN_PD3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 3U)
#define BSP_GPIO_PIN_PD4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 4U)
#define BSP_GPIO_PIN_PD5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 5U)
#define BSP_GPIO_PIN_PD6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 6U)
#define BSP_GPIO_PIN_PD7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 7U)
#define BSP_GPIO_PIN_PD8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 8U)
#define BSP_GPIO_PIN_PD9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 9U)
#define BSP_GPIO_PIN_PD10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 10U)
#define BSP_GPIO_PIN_PD11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 11U)
#define BSP_GPIO_PIN_PD12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 12U)
#define BSP_GPIO_PIN_PD13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 13U)
#define BSP_GPIO_PIN_PD14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 14U)
#define BSP_GPIO_PIN_PD15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_D, 15U)

#define BSP_GPIO_PIN_PE0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 0U)
#define BSP_GPIO_PIN_PE1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 1U)
#define BSP_GPIO_PIN_PE2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 2U)
#define BSP_GPIO_PIN_PE3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 3U)
#define BSP_GPIO_PIN_PE4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 4U)
#define BSP_GPIO_PIN_PE5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 5U)
#define BSP_GPIO_PIN_PE6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 6U)
#define BSP_GPIO_PIN_PE7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 7U)
#define BSP_GPIO_PIN_PE8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 8U)
#define BSP_GPIO_PIN_PE9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 9U)
#define BSP_GPIO_PIN_PE10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 10U)
#define BSP_GPIO_PIN_PE11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 11U)
#define BSP_GPIO_PIN_PE12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 12U)
#define BSP_GPIO_PIN_PE13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 13U)
#define BSP_GPIO_PIN_PE14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 14U)
#define BSP_GPIO_PIN_PE15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_E, 15U)

#define BSP_GPIO_PIN_PF0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 0U)
#define BSP_GPIO_PIN_PF1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 1U)
#define BSP_GPIO_PIN_PF2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 2U)
#define BSP_GPIO_PIN_PF3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 3U)
#define BSP_GPIO_PIN_PF4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 4U)
#define BSP_GPIO_PIN_PF5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 5U)
#define BSP_GPIO_PIN_PF6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 6U)
#define BSP_GPIO_PIN_PF7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 7U)
#define BSP_GPIO_PIN_PF8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 8U)
#define BSP_GPIO_PIN_PF9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 9U)
#define BSP_GPIO_PIN_PF10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 10U)
#define BSP_GPIO_PIN_PF11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 11U)
#define BSP_GPIO_PIN_PF12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 12U)
#define BSP_GPIO_PIN_PF13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 13U)
#define BSP_GPIO_PIN_PF14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 14U)
#define BSP_GPIO_PIN_PF15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_F, 15U)

#define BSP_GPIO_PIN_PG0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 0U)
#define BSP_GPIO_PIN_PG1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 1U)
#define BSP_GPIO_PIN_PG2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 2U)
#define BSP_GPIO_PIN_PG3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 3U)
#define BSP_GPIO_PIN_PG4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 4U)
#define BSP_GPIO_PIN_PG5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 5U)
#define BSP_GPIO_PIN_PG6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 6U)
#define BSP_GPIO_PIN_PG7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 7U)
#define BSP_GPIO_PIN_PG8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 8U)
#define BSP_GPIO_PIN_PG9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 9U)
#define BSP_GPIO_PIN_PG10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 10U)
#define BSP_GPIO_PIN_PG11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 11U)
#define BSP_GPIO_PIN_PG12 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 12U)
#define BSP_GPIO_PIN_PG13 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 13U)
#define BSP_GPIO_PIN_PG14 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 14U)
#define BSP_GPIO_PIN_PG15 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_G, 15U)

#define BSP_GPIO_PIN_PH0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_H, 0U)
#define BSP_GPIO_PIN_PH1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_H, 1U)

#define BSP_GPIO_PIN_PI0 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 0U)
#define BSP_GPIO_PIN_PI1 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 1U)
#define BSP_GPIO_PIN_PI2 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 2U)
#define BSP_GPIO_PIN_PI3 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 3U)
#define BSP_GPIO_PIN_PI4 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 4U)
#define BSP_GPIO_PIN_PI5 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 5U)
#define BSP_GPIO_PIN_PI6 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 6U)
#define BSP_GPIO_PIN_PI7 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 7U)
#define BSP_GPIO_PIN_PI8 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 8U)
#define BSP_GPIO_PIN_PI9 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 9U)
#define BSP_GPIO_PIN_PI10 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 10U)
#define BSP_GPIO_PIN_PI11 BSP_GPIO_PIN(WD_BSP_GPIO_PORT_I, 11U)

// Types
typedef size_t BspGpioPin;

typedef enum bsp_gpio_port_t
{
    WD_BSP_GPIO_PORT_A = 0,
    WD_BSP_GPIO_PORT_B,
    WD_BSP_GPIO_PORT_C,
    WD_BSP_GPIO_PORT_D,
    WD_BSP_GPIO_PORT_E,
    WD_BSP_GPIO_PORT_F,
    WD_BSP_GPIO_PORT_G,
    WD_BSP_GPIO_PORT_H,
    WD_BSP_GPIO_PORT_I
} BspGpioPort;

// Interface
const GpioOps *bsp_gpio_ops(void);
BspGpioPort bsp_gpio_pin_port(BspGpioPin pin);
size_t bsp_gpio_pin_index(BspGpioPin pin);
GpioConfig bsp_gpio_input_config(GpioPull pull);
GpioConfig bsp_gpio_output_config(GpioOutputType output_type, GpioSpeed speed, GpioLevel level);
GpioConfig bsp_gpio_alternate_config(GpioAlternate alternate, GpioPull pull, GpioSpeed speed, GpioOutputType output_type, GpioLevel level);
GpioConfig bsp_gpio_analog_config(void);

#endif
